# Auto-generated by /home/cx/mCode/uefiSdkForBarrelfish/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/cx/mCode/uefiSdkForBarrelfish
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/cx/mCode/uefiSdkForBarrelfish/BaseTools
fi
if [ -e /home/cx/mCode/uefiSdkForBarrelfish/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/cx/mCode/uefiSdkForBarrelfish/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/cx/mCode/uefiSdkForBarrelfish/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
